services:
  reminder-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reminder-bot
    restart: always
    environment:
      - BOT_TOKEN=insert-token
      - DATABASE_PATH=/app/data/reminder.db
      - DEFAULT_NOTIFY_TIME=09:00
    volumes:
      - ./data:/app/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge